apiVersion: v1
kind: Pod
metadata:
  name: another-pod
spec:
  containers:
  - name: mongo
    image: mongo:4.0.17
    ports:
    - containerPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: some-username
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: some-password
