apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sts
spec:
  serviceName: database
  replicas: 3
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
        selector: mongodb-sts
    spec:
      containers:
      - name: mongo-cnt
        image: mongo:4.0.8
        volumeMounts:
        - name: db-volume
          mountPath: /data/db
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: password
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 200Mi
